### PR TITLE
Enterprise batch support

### PR DESCRIPTION
**Pull request by Ch4s3**
This PR adds support for the enterprise batching functionality.

The functionality is loosely based on the official libraries, but attempts to stick to the existing patterns here.

Note that we have excluded the batch tests from CI because they require an enterprise version of faktory to run. Perhaps we could later ask contribsys to provide a key for testing here.

### CODE REVIEW

**Comment by Ch4s3** [comment]
> Hey thanks for the PR!
> 
> At Seated we are not using the batch feature from enterprise. In fact this comes at the point where we have almost completed the transition of our app from Faktory to Oban. We don't want to stand in the way here so are you guys at Pepsi interested in taking over the project seeing as we won't be actively maintaining the library any further?

Let me look into it. 

The easiest thing is probably to move it to a new org, and give some of us commit access.

**Comment by john-griffin** [comment]
Thanks, works for me, just let me know!

**Comment by Ch4s3** [comment]
Cool, let me think of a good org name and create one to transfer this too. That seems like the most expedient path.

**Comment by Ch4s3** [comment]
@john-griffin you can transfer to https://github.com/opt-elixir and maybe add me in hex.pm. I'll rope some other folks in and make sure this gets taken care of.

**Comment by john-griffin** [comment]
@Ch4s3 thanks. I've made you an owner on hex and made you an admin of this repo. You should be able to transfer it to opt-elixir now.

**Comment by Ch4s3** [comment]
@john-griffin Thanks! If you folks ever move back to using this, let me know.

**Pull request merged**
